#!/bin/bash
echo aaa > /tmp/b
export QT_QPA_PLATFORM=wayland
export XDG_SESSION_TYPE=wayland
export WAYLAND_DISPLAY=wayland-0
export DISPLAY=:0
deepin-kwin_wayland --drm --xwayland &
sleep 5
startdde
killall deepin-kwin_wayland
